version: '2'
services:
  myproject:
    build: ./ 
    container_name: Laravel
    restart: always
    volumes:
      - ./code:/var/www/html
    ports:
      - 8001:8000
    networks:
      - frontend

  db:
      image: mysql:8.0
      container_name: db-lar
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: laravel-db
        MYSQL_USER: francesco
        MYSQL_PASSWORD: root
      ports:
        - "6034:3306"
      networks:
        - frontend

  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma-lar
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80
      networks:
        - frontend
  queue_worker: 
    build: ./
    container_name: queue_worker
    restart: always
    volumes:  
      - ./code:/var/www/html
    ports:
      - 8020:8000
    networks:
      - backend

      

  ### Shared services

  redis:
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - frontend
      - backend

      
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.21.0.0/16
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.22.0.0/16
