version: '2'
services:
  myproject:
    build: ./ 
    container_name: Laravel-Web
    restart: always
    volumes:
      - ./code:/var/www/html
    ports:
      - 80:80
      - 8001:8000
  db:
      image: mysql:8.0
      container_name: db-laravel
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: laravel-db
        MYSQL_USER: francesco
        MYSQL_PASSWORD: root
      ports:
        - "6034:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: pma-laravel
      links:
        - db
      environment:
        PMA_HOST: db
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
      restart: always
      ports:
        - 8081:80